version: 2.1
jobs:
  setup_and_deploy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    working_directory: terraform/
    steps:
      - checkout
      - run:
          name: Terraform Deploy Commands
          command: |
            terraform init
            terraform fmt
            terraform validate
            terraform plan
            terraform apply --auto-approve
            
          
workflows:
  build-and-deploy-to-koyeb:
    jobs:
      - setup_and_deploy:
          context: PROJECTS